name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: 85e4706f-4467-45f6-887b-5e7ea96fb1e3-
          heroku_app_name: "file-to-link-09" #Must be unique in Heroku
          heroku_email: "autofilterbotv2@gmail.com"
      #    usedocker: true
